### ISSUE TITLE
peerDependenciesが指定されている理由について

### ISSUE THREAD

**Issue by aaharu** [fincode-byGMO/fincode-sdk-node#3]
`@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser`, `typescript` が peerDependencies として指定されている理由はなんでしょうか。
パッケージマネージャーの設定次第ではありますが、デフォルトでは peerDependencies も含めてインストールされることが多いので、 `@fincode/node` のパッケージ利用者側にも上記依存がインストールされてしまいます。

**Comment by aaharu** [comment]
v1.1.0 で `peerDependencies` がなくなっているようなのでクローズします。

**Comment by fincode-developer** [comment]
@aaharu 
ご指摘いただきありがとうございました。
また何か気になる点があれば、お気軽にお知らせください。
